version: "3.7"
name: rolebot
services:
  bot:
    build: .
    restart: always
    entrypoint: sh -c "sleep 5 && npm run migration:run && node build/index.js"
    env_file: .env
    links:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: RoleBot
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    command: --default-authentication-plugin=mysql_native_password

#  phpmyadmin:
#    image: phpmyadmin
#    restart: always
#    ports:
#      - 8080:80
#    environment:
#      - PMA_HOST=mysql

volumes:
  mysql:
